name: .NET 9 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore DotNet9CITest.sln

    - name: Build solution
      run: dotnet build DotNet9CITest.sln --no-restore

    - name: Run unit tests
      run: dotnet test App.Tests/App.Tests.csproj --no-build --verbosity normal

    - name: Publish app (Release configuration)
      run: dotnet publish DotNet9CITest.sln -c Release -o ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3.0.0
      with:
        name: dotnet-publish-files
        path: ./publish
